import * as apiCategory from './category';
import * as apiProduct from './product';
import * as apiLogin from './login';
import * as apiCart from './cart';
import * as apiOrderDetail from './orderDetail';
import * as apiRating from './rating';
import * as apiRegister from './register';
import * as apiProfile from './profile';
import * as apiAdmin from './admin';
import * as apiUploadImage from './uploadImage';
import * as apiPayment from './payment';
export { apiCategory, apiProduct, apiLogin, apiCart, apiOrderDetail, apiRating, apiRegister, apiProfile, apiAdmin,apiUploadImage,apiPayment };