import * as apiCategory from './category';
import * as apiProduct from './product';
import * as apiLogin from './login';
import * as apiCart from './cart';
import * as apiOrderDetail from './orderDetail';
import * as apiRating from './rating';
import * as apiRegister from './register';
import * as apiProfile from './profile';
import * as apiUploadImage from './uploadImage';
import * as apiPayment from './payment';
import * as apiUser from './user';
import * as apiSize from './size';
import * as apiColor from './color';
import * as apiImage from './image';
import * as apiAccount from './account';
import * as apiEmail from './email';
export { apiCategory, apiProduct, apiLogin, apiCart, apiOrderDetail, apiRating, apiRegister, apiProfile,apiUploadImage,apiPayment,apiUser,apiSize,apiColor,apiImage,apiAccount,apiEmail };